//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Product_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int IDPCard { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Tel { get; set; }
    }
}
