//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1_WCF_.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibraryPerson")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGetFriends")]
    public interface IGetFriends {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetFriends/GetPeople", ReplyAction="http://tempuri.org/IGetFriends/GetPeopleResponse")]
        ConsoleApplication1_WCF_.ServiceReference1.Person[] GetPeople(ConsoleApplication1_WCF_.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetFriends/GetPeople", ReplyAction="http://tempuri.org/IGetFriends/GetPeopleResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1_WCF_.ServiceReference1.Person[]> GetPeopleAsync(ConsoleApplication1_WCF_.ServiceReference1.Person p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetFriendsChannel : ConsoleApplication1_WCF_.ServiceReference1.IGetFriends, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFriendsClient : System.ServiceModel.ClientBase<ConsoleApplication1_WCF_.ServiceReference1.IGetFriends>, ConsoleApplication1_WCF_.ServiceReference1.IGetFriends {
        
        public GetFriendsClient() {
        }
        
        public GetFriendsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetFriendsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetFriendsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetFriendsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1_WCF_.ServiceReference1.Person[] GetPeople(ConsoleApplication1_WCF_.ServiceReference1.Person p) {
            return base.Channel.GetPeople(p);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1_WCF_.ServiceReference1.Person[]> GetPeopleAsync(ConsoleApplication1_WCF_.ServiceReference1.Person p) {
            return base.Channel.GetPeopleAsync(p);
        }
    }
}
