//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_UI_.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedUnits", Namespace="http://schemas.datacontract.org/2004/07/Converter")]
    [System.SerializableAttribute()]
    public partial class ConvertedUnits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CelsiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FahrenheitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double footField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double inchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double yardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Celsius {
            get {
                return this.CelsiusField;
            }
            set {
                if ((this.CelsiusField.Equals(value) != true)) {
                    this.CelsiusField = value;
                    this.RaisePropertyChanged("Celsius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Fahrenheit {
            get {
                return this.FahrenheitField;
            }
            set {
                if ((this.FahrenheitField.Equals(value) != true)) {
                    this.FahrenheitField = value;
                    this.RaisePropertyChanged("Fahrenheit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double foot {
            get {
                return this.footField;
            }
            set {
                if ((this.footField.Equals(value) != true)) {
                    this.footField = value;
                    this.RaisePropertyChanged("foot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double inch {
            get {
                return this.inchField;
            }
            set {
                if ((this.inchField.Equals(value) != true)) {
                    this.inchField = value;
                    this.RaisePropertyChanged("inch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double yard {
            get {
                return this.yardField;
            }
            set {
                if ((this.yardField.Equals(value) != true)) {
                    this.yardField = value;
                    this.RaisePropertyChanged("yard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LinearMeasure", ReplyAction="http://tempuri.org/IService1/LinearMeasureResponse")]
        Wpf_UI_.ServiceReference1.ConvertedUnits LinearMeasure(double meters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LinearMeasure", ReplyAction="http://tempuri.org/IService1/LinearMeasureResponse")]
        System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> LinearMeasureAsync(double meters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        Wpf_UI_.ServiceReference1.ConvertedUnits CelsiusToFahrenheit(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> CelsiusToFahrenheitAsync(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        Wpf_UI_.ServiceReference1.ConvertedUnits FahrenheitToCelsius(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> FahrenheitToCelsiusAsync(double f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Wpf_UI_.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Wpf_UI_.ServiceReference1.IService1>, Wpf_UI_.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wpf_UI_.ServiceReference1.ConvertedUnits LinearMeasure(double meters) {
            return base.Channel.LinearMeasure(meters);
        }
        
        public System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> LinearMeasureAsync(double meters) {
            return base.Channel.LinearMeasureAsync(meters);
        }
        
        public Wpf_UI_.ServiceReference1.ConvertedUnits CelsiusToFahrenheit(double c) {
            return base.Channel.CelsiusToFahrenheit(c);
        }
        
        public System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> CelsiusToFahrenheitAsync(double c) {
            return base.Channel.CelsiusToFahrenheitAsync(c);
        }
        
        public Wpf_UI_.ServiceReference1.ConvertedUnits FahrenheitToCelsius(double f) {
            return base.Channel.FahrenheitToCelsius(f);
        }
        
        public System.Threading.Tasks.Task<Wpf_UI_.ServiceReference1.ConvertedUnits> FahrenheitToCelsiusAsync(double f) {
            return base.Channel.FahrenheitToCelsiusAsync(f);
        }
    }
}
